net.sf.jasperreports.extension.registry.factory.deserialization.whitelist=net.sf.jasperreports.engine.util.StandardDeserializationClassWhitelistExtension
net.sf.jasperreports.deserialization.class.whitelist.jasperreports.javascript=\
	net.sf.jasperreports.javascript.JavaScriptCompiledData*
