net.sf.jasperreports.extension.registry.factory.barcode4j=net.sf.jasperreports.barcode4j.Barcode4JExtensionsRegistryFactory

net.sf.jasperreports.extension.registry.factory.deserialization.whitelist=net.sf.jasperreports.engine.util.StandardDeserializationClassWhitelistExtension
net.sf.jasperreports.deserialization.class.whitelist.jasperreports.barcode4j=\
	net.sf.jasperreports.barcode4j.*Component,\
	net.sf.jasperreports.barcode4j.*Enum
