net.sf.jasperreports.extension.registry.factory.barbecue=net.sf.jasperreports.barbecue.BarbecueExtensionsRegistryFactory

net.sf.jasperreports.extension.registry.factory.deserialization.whitelist=net.sf.jasperreports.engine.util.StandardDeserializationClassWhitelistExtension
net.sf.jasperreports.deserialization.class.whitelist.jasperreports.barbecue=\
	net.sf.jasperreports.barbecue.BarbecueRendererImpl,\
	net.sf.jasperreports.barbecue.StandardBarbecueComponent,\
	net.sourceforge.barbecue.Barcode,\
	net.sourceforge.barbecue.**.*Barcode
