net.sf.jasperreports.extension.registry.factory.xchart=xchart.XChartExtensions

net.sf.jasperreports.extension.registry.factory.deserialization.whitelist=net.sf.jasperreports.engine.util.StandardDeserializationClassWhitelistExtension
net.sf.jasperreports.deserialization.class.whitelist.jasperreports.xchartcomponent=\
	xchart.CompiledXYDataset,\
	xchart.DesignXYSeries,\
	xchart.XYChartComponent
